version: '3'

services:
    app:
      build: .
      volumes:
         - .:/usr/src/app
         - /etc/localtime:/etc/localtime:ro
      container_name: book_recommender

networks:
  default:
    external:
      name: proxy_network

